check if required programs are installed

diff --git a/initrdbo b/initrdbo
--- a/initrdbo
+++ b/initrdbo
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-# Required programs: mount awk tr lddtree cpio "$COMPRESSOR"
-
 header="
   _      _ _          _ _         
  (_)_ _ (_) |_ _ _ __| | |__  ___ 
@@ -18,6 +16,7 @@ INITRAMFS_OUT="/boot/initramfs-$KERNEL_RELEASE"
 MODULES_FILE="/etc/modules"
 KEEP_TMPDIR="no"
 COMPRESSOR="xz" # The compressor is expanded, so you can pass arguments to it like `xz -z -9`
+SKIP_CHECKS="no"
 
 help="
 usage: initrdbo [[ARGS]] [INITRAMFS_OUT]
@@ -37,6 +36,7 @@ OPTIONS:
                          (Default: $MODULES_FILE)
         -z [COMPRESSOR]  Sets the initramfs compressor
                          (Default: $COMPRESSOR)
+  -n               Skip checks before making initramfs
 
 	[INITRAMFS_OUT]: Output file of the initramfs
 	                 (Current: $INITRAMFS_OUT)
@@ -47,6 +47,15 @@ usage() {
 	exit 1
 }
 
+check_programs() {
+	for prog in mount awk tr lddtree cpio "$COMPRESSOR"; do
+		if ! which "$prog" > /dev/null 2>&1; then
+			echo "[!] Missing program '$prog', cannot continue"
+			exit 1
+		fi
+	done
+}
+
 parse_args() {
 	INITRAMFS_OUT=""
 	
@@ -55,6 +64,7 @@ parse_args() {
 		case "$arg" in
 		-h|--help) usage;;
 		-K) KEEP_TMPDIR="yes";;
+		-n) SKIP_CHECKS="yes";;
 		-k|-c|-m|-z) prev="$arg";;
 		*)
 			case "$prev" in
@@ -93,7 +103,12 @@ copy_kernel_modules() {
 	# Copy Linux kernel modules by file match
 	local kmods=$(cat "$modules_file" | grep ^kernel/ | tr '\n' ' ' | xargs -0 printf "%s\n")
 	for match in $kmods; do
-		local files="$(find "$root_dir/lib/modules/$kernel_release/"$match)"
+		match_path="$root_dir/lib/modules/$kernel_release/"$match
+		if [ ! -e "$match_path" ]; then
+			echo "[!] '$match' was not found and got skipped"
+			continue
+		fi
+		local files="$(find "$match_path")"
 		for file in $files; do
 			local file="$(printf "$file" | sed "s|.*/lib/modules/$kernel_release/||")"
 			local directory=$(printf $file | awk -F '/' '{ $NF=""; print $0 }' | tr ' ' '/')
@@ -163,6 +178,13 @@ echo "MODULES_FILE=$MODULES_FILE"
 echo "KEEP_TMPDIR=$KEEP_TMPDIR"
 echo
 
+if [ "$SKIP_CHECKS" = "no" ]; then
+	echo "[*] Checking dependencies..."
+	check_programs
+else
+	echo "[*] Skipped checks"
+fi
+
 echo "[*] Creating temporary directory for initrd..."
 
 tmpdir="$(mktemp -d)"
@@ -172,6 +194,8 @@ echo "[*] Copying kernel modules to initrd dir..."
 for file in $(ls "$CONFIG_DIR" | grep '.modules$'); do
 	copy_kernel_modules "$tmpdir" "$CONFIG_DIR/$file" "$ROOT_DIR" "$KERNEL_RELEASE"
 done
+
+echo "[*] Copying required firmware to initrd dir..."
 
 echo "[*] Copying required files to initrd dir..."
 for file in $(ls "$CONFIG_DIR" | grep '.files$'); do
